# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RookkaProject', '0002_auto_20171130_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='query',
        ),
        migrations.DeleteModel(
            name='Query',
        ),
    ]
